- name: Setup frontend
  hosts: all
  become: true
  tasks:
    - name: Install the latest version of Nginx
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: Remove file (delete file)
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

# echo -e "${color} uploading the content ${nocolor}"
# curl -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}.zip &>>${log_file}
# stat_check $?

# echo -e "${color} unzip the frontenf content ${nocolor}"
# cd /usr/share/nginx/html &>>${log_file}
# unzip /tmp/${component}.zip &>>${log_file}
# stat_check $?

# echo -e "${color} Config the Roboshop file ${nocolor}"
# cp /home/centos/shell-oct/roboshop.conf /etc/nginx/default.d/roboshop.conf 
# stat_check $?

# echo -e "${color} systemd start ${nocolor}"
# systemctl enable nginx &>>${log_file}
# systemctl restart nginx &>>${log_file}
# stat_check $?
        